version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  example-job:
    docker:
      - image: cimg/base:stable
    steps:
      - docker/build:
          attach-at: ./ 
          docker-context: . 
          dockerfile: Dockerfile 
          image: ozeliurs-com 
          path: . 
          step-name: Docker-Build 

workflows:
  example-workflow:
    jobs:
      - example-job