name: Python Code CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
    - name: Install pylint
      run: pip install pylint
    - name: Install Requirements
      run: pip3 install -r requirements.txt
    - name: Test main.py
      run: pylint main:app
